# Generated by Django 2.2.1 on 2021-01-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='苹果', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bzq', models.IntegerField(default=30)),
                ('scrq', models.DateField(blank=True, null=True)),
                ('desc', models.CharField(default='商品描述....', max_length=128)),
                ('content', models.TextField(default='商品详情...')),
                ('image', models.ImageField(default='1.jpg', upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('logo', models.ImageField(default='1.jpg', upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='zs', max_length=32)),
                ('password', models.CharField(default='222', max_length=64)),
                ('phone', models.CharField(default='110', max_length=32)),
                ('address', models.CharField(default='北京市', max_length=128)),
                ('gender', models.BooleanField(default=True)),
                ('headimg', models.ImageField(default='1.jpg', upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='我的小店', max_length=32)),
                ('address', models.CharField(default='广州', max_length=128)),
                ('desc', models.CharField(default='不咋地', max_length=128)),
                ('logo', models.ImageField(default='1.jpg', upload_to='img')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller')),
            ],
        ),
        migrations.DeleteModel(
            name='Suser',
        ),
        migrations.AddField(
            model_name='goods',
            name='goodstype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.GoodsType'),
        ),
        migrations.AddField(
            model_name='goods',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Store'),
        ),
    ]
