# Generated by Django 2.2.1 on 2021-01-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20210125_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='logo',
            field=models.ImageField(default='1.jpg', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(default='1.jpg', upload_to='img'),
        ),
    ]
