# Generated by Django 2.2.1 on 2021-01-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_auto_20210125_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='seller/goodsimg'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='logo',
            field=models.ImageField(default='1.jpg', upload_to='seller/goodstypeimg'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='headimg',
            field=models.ImageField(default='1.jpg', upload_to='seller/headimg'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(default='1.jpg', upload_to='seller/storeimg'),
        ),
    ]
